import { GetServerSideProps } from "next";
import Head from "next/head";
import Link from "next/link";
import NewActivityForm from "../../../../../../components/contents/activityform/new_activity_form";
import ConfirmActionModal from "../../../../../../components/utils/confirm_action_modal";
import PageHeader from "../../../../../../components/utils/page_header";
import { useSelector, useDispatch } from "react-redux";
import {
  setType,
  setTitle,
  ActivitiesState,
} from "../../../../../../redux/features/activitiesSlice";
import { useEffect, useState } from "react";
import ErrorModal from "../../../../../../components/utils/error_modal";
import SuccessModal from "../../../../../../components/utils/success_modal";
import LoadingModal from "../../../../../../components/utils/loading_modal";
import { activities_type } from "../index";
import { RootState } from "../../../../../../redux/store";
import ActivitiesService from "../../../../../../services/activities.service";
import { ActiveClassState } from "../../../../../../redux/features/active_class";
import ErrorCard from "../../../../../../components/utils/error_card";
import Loading from "../../../../../../components/utils/loading";

export type ActivityType = {
  id: number;
  type: string;
  activity_number: number;
  title: string;
  createdAt: string;
  updatedAt: string;
  weekcontent_id: number;
};

interface EditActivityProps {
  activity_id: number;
}

export default function EditActivity({ activity_id }: EditActivityProps) {
  const activities_state = useSelector<RootState, ActivitiesState>(
    (state) => state.activities
  );
  const dispatch = useDispatch();

  const [show_confirm_action_modal, setShowConfirmActionModal] =
    useState(false);
  const [errorMessage, setErrorMessage] = useState("");
  const [successMessage, setSuccessMessage] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [isPageLoading, setIsPageLoading] = useState(false);
  const { id: class_id } = useSelector<RootState, ActiveClassState>(
    (state) => state.active_class
  );
  const [activity, setActivity] = useState<ActivityType>({
    id: -1,
    type: "",
    activity_number: 0,
    title: "",
    createdAt: "",
    updatedAt: "",
    weekcontent_id: 0,
  });
  const [error, setError] = useState(false);

  const updateActivity = async () => {
    setShowConfirmActionModal(false);
    setIsLoading(true);

    const update_activity_response = await ActivitiesService.updateActivity(
      class_id,
      activity.id,
      activities_state.type,
      activities_state.title
    );

    setIsLoading(false);

    if (update_activity_response.error) {
      // An error occured
      setErrorMessage(
        "Aconteceu um erro ao atualizar a atividade. Por favor tente novamente."
      );
    } else {
      // Activity updated successfully
      setSuccessMessage(
        "A atividade do tipo " +
          activities_type[activities_state.type] +
          " foi atualizada com sucesso!"
      );
    }
  };

  useEffect(() => {
    setIsPageLoading(true);
    ActivitiesService.getActivity(class_id, activity_id)
      .then((data) => {
        setActivity(data);
        dispatch(setType(data.type));
        dispatch(setTitle(data.title));
      })
      .catch((err) => {
        setError(true);
      })
      .finally(() => {
        setIsPageLoading(false);
      });
  }, [activity_id, class_id, dispatch]);

  return (
    <>
      <Head>
        <title>UNO - Conteúdos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container px-4">
        <div className="row g-3 mt-2 mb-4">
          <PageHeader
            header_text={`${activity.activity_number}. Atividade - Editar`}
          />
        </div>

        <div className="row g-3 mt-2 mb-4">
          {error && (
            <div className="row g-3 my-2">
              <ErrorCard message="Ocorreu um erro ao obter a atividade. Por favor tente novamente." />
            </div>
          )}
          {!error && <NewActivityForm />}
        </div>

        <div className="row g-3 my-2">
          <div className="col gap-3 d-flex justify-content-end">
            <button
              className="btn btn-success"
              onClick={() => setShowConfirmActionModal(true)}
            >
              Concluir
            </button>
            <Link href={`/contents/weeks/edit/${activity.weekcontent_id}`}>
              <button className="btn btn-danger">Cancelar</button>
            </Link>
          </div>
        </div>
      </div>

      <ErrorModal
        show={errorMessage !== ""}
        onHide={() => setErrorMessage("")}
        message={errorMessage}
      />
      <SuccessModal
        show={successMessage !== ""}
        onHide={() => setSuccessMessage("")}
        message={successMessage}
        button_link_path={`/contents/weeks/edit/${activity.weekcontent_id}`}
      />
      {isLoading && <LoadingModal />}
      <ConfirmActionModal
        message={`Tem a certeza que pretende atualizar a atividade?`}
        onHide={() => setShowConfirmActionModal(false)}
        show={show_confirm_action_modal}
        confirmAction={() => updateActivity()}
      />
      {isPageLoading && <Loading />}
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const activity_id = context.query.activity_id;

  return {
    props: {
      activity_id: activity_id,
    },
  };
};
