import { GetServerSideProps } from "next";
import Head from "next/head";
import Link from "next/link";
import NewActivityForm from "../../../../../../components/contents/activityform/new_activity_form";
import ConfirmActionModal from "../../../../../../components/utils/confirm_action_modal";
import PageHeader from "../../../../../../components/utils/page_header";
import { useSelector, useDispatch } from "react-redux";
import { activitiesState } from "../../../../../../redux/features/activitiesSlice";
import { useState } from "react";
import ErrorModal from "../../../../../../components/utils/error_modal";
import SuccessModal from "../../../../../../components/utils/success_modal";
import LoadingModal from "../../../../../../components/utils/loading_modal";

interface ContentWeekProps {
  weekcontent_id: number;
}

export default function NewActivity({ weekcontent_id }: ContentWeekProps) {
  const dispatch = useDispatch();
  const activities_state = useSelector(activitiesState);

  const [show_confirm_action_modal, setShowConfirmActionModal] =
    useState(false);
  const [errorMessage, setErrorMessage] = useState("");
  const [successMessage, setSuccessMessage] = useState("");
  const [isLoading, setIsLoading] = useState(false);

  const createNewActivity = async () => {
    setShowConfirmActionModal(false);
    setIsLoading(true);

    const payload = {
      type: activities_state.type,
      weekcontent_id: weekcontent_id,
      title: activities_state.title,
    };

    let new_activity_response = await fetch("/api/contents/activities/create_activity", {
      method: "POST",
      body: JSON.stringify(payload),
    });

    setIsLoading(false);

    if (new_activity_response.status !== 200) {
      // An error occured
      setErrorMessage(
        "Aconteceu um erro ao criar a nova atividade. Por favor tente novamente."
      );
    } else {
      // Activity created successfully
      let results = await new_activity_response.json();
      setSuccessMessage(
        "A atividade do tipo " + payload.type + " foi criada com sucesso!"
      );
    }
  };

  return (
    <>
      <Head>
        <title>UNO - Conteúdos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container px-4">
        <div className="row g-3 mt-2 mb-4">
          <PageHeader header_text={"Nova Atividade"} />
        </div>

        <div className="row g-3 mt-2 mb-4">
          <NewActivityForm />
        </div>

        <div className="row g-3 my-2">
          <div className="col gap-3 d-flex justify-content-end">
            <button className="btn btn-success" onClick={() => setShowConfirmActionModal(true)}>Concluir</button>
            <Link href={`/contents/weeks/edit/${weekcontent_id}`}>
              <button className="btn btn-danger">Cancelar</button>
            </Link>
          </div>
        </div>
      </div>

      <ErrorModal
        show={errorMessage !== ""}
        onHide={() => setErrorMessage("")}
        message={errorMessage}
      />
      <SuccessModal
        show={successMessage !== ""}
        onHide={() => setSuccessMessage("")}
        message={successMessage}
      />
      {isLoading && <LoadingModal />}
      <ConfirmActionModal
        message={`Tem a certeza que pretende criar uma atividade do tipo ${activities_state.type}?`}
        onHide={() => setShowConfirmActionModal(false)}
        show={show_confirm_action_modal}
        confirmAction={() => createNewActivity()}
      />
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const weekcontent_id = context.query.id;

  return {
    props: {
      weekcontent_id: weekcontent_id,
    },
  };
};
