import Head from "next/head";
import { useEffect, useState } from "react";
import { useSelector } from "react-redux";
import ContentCard from "../../../components/contents/content_card";
import NewCardWithTextInput from "../../../components/contents/new_card_with_text_input";
import ConfirmActionModal from "../../../components/utils/confirm_action_modal";
import ErrorCard from "../../../components/utils/error_card";
import ErrorModal from "../../../components/utils/error_modal";
import Loading from "../../../components/utils/loading";
import LoadingModal from "../../../components/utils/loading_modal";
import PageHeaderButtonCard from "../../../components/utils/page_header_button_card";
import SuccessModal from "../../../components/utils/success_modal";
import { ActiveClassState } from "../../../redux/features/active_class";
import { RootState } from "../../../redux/store";
import ActivityGroupsService from "../../../services/activitygroups.service";

export type ActivityGroupsType = {
  id: number;
  name: string;
  order: number;
  number_of_videos: number;
  number_of_exercises: number;
  createdAt: string;
  updatedAt: string;
};

export default function ActivityGroup() {
  // On Page Load
  const [isPageLoading, setIsPageLoading] = useState(false);
  const [error, setError] = useState(false);

  // On User interaction
  const [isLoading, setIsLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState("");
  const [successMessage, setSuccessMessage] = useState("");
  const [confirmDeleteGroup, setConfirmDeleteGroup] = useState({
    activitygroup_id: -1,
    order: -1,
  });
  const [newActivityGroupMode, setNewActivityGroupMode] = useState(false);

  // Page Data
  const [activityGroups, setActivityGroups] = useState<
    Array<ActivityGroupsType>
  >([]);

  // Class state (Redux)
  const { id: class_id } = useSelector<RootState, ActiveClassState>(
    (state) => state.active_class
  );

  const createNewActivityGroup = async (name: string) => {
    setIsLoading(true);

    const new_activitygroup_response =
      await ActivityGroupsService.createActivityGroup(class_id, name, 0, 0);

    setIsLoading(false);

    if (new_activitygroup_response.error) {
      // An error occured
      setErrorMessage(
        "Aconteceu um erro ao criar um novo grupo de atividades. Por favor tente novamente."
      );
    } else {
      // ActivityGroup created successfully
      activityGroups.push(new_activitygroup_response);
      setActivityGroups([...activityGroups]);
      setSuccessMessage(
        "O grupo de atividades com o nome " +
          new_activitygroup_response.name +
          " foi criado com sucesso!"
      );
    }
  };

  const deleteActivityGroup = async ({
    activitygroup_id,
    order,
  }: {
    activitygroup_id: number;
    order: number;
  }) => {
    setIsLoading(true);

    const delete_activitygroup_response =
      await ActivityGroupsService.deleteActivityGroup(
        class_id,
        activitygroup_id
      );

    setIsLoading(false);

    if (delete_activitygroup_response.error) {
      // An error occured
      setErrorMessage(
        "Aconteceu um erro ao apagar o grupo de atividades. Por favor tente novamente."
      );
    } else {
      // ActivityGroup deleted successfully
      setSuccessMessage(
        "O grupo de atividades " + order + " foi eliminado com sucesso!"
      );
      let _activityGroups = activityGroups;
      _activityGroups.splice(order - 1, 1);
      for (let idx = order - 1; idx < _activityGroups.length; idx++) {
        _activityGroups[idx].order -= 1;
      }
      setActivityGroups(_activityGroups);
    }
    setConfirmDeleteGroup({ activitygroup_id: -1, order: -1 });
  };

  useEffect(() => {
    setIsPageLoading(true);
    ActivityGroupsService.getActivityGroups(class_id)
      .then((data) => {
        setActivityGroups(data);
      })
      .catch((err) => {
        setError(true);
      })
      .finally(() => {
        setIsPageLoading(false);
      });
  }, [class_id]);

  if (isPageLoading) return <Loading />;

  return (
    <>
      <Head>
        <title>UNO - Conteúdos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container px-4">
        <div className="row g-3 mt-2 mb-4">
          <PageHeaderButtonCard
            header_text="Grupos de atividades"
            button_text="Novo grupo"
            button_action={() => setNewActivityGroupMode(true)}
          />
        </div>
        {error && (
          <div className="row g-3 my-2">
            <ErrorCard message="Ocorreu um erro ao obter os grupos de atividades. Por favor tente novamente." />
          </div>
        )}
        {newActivityGroupMode && (
          <div className="row g-3 my-1">
            <NewCardWithTextInput
              confirm={createNewActivityGroup}
              cancel={() => setNewActivityGroupMode(false)}
            />
          </div>
        )}
        {activityGroups.map(function (
          activityGroup: ActivityGroupsType,
          index
        ) {
          return (
            <div className="row g-3 my-1" key={activityGroup.id}>
              <ContentCard
                id={activityGroup.id}
                name={activityGroup.name}
                order={activityGroup.order}
                setConfirmActionWeek={setConfirmDeleteGroup}
              />
            </div>
          );
        })}
      </div>

      <ErrorModal
        show={errorMessage !== ""}
        onHide={() => setErrorMessage("")}
        message={errorMessage}
      />
      <SuccessModal
        show={successMessage !== ""}
        onHide={() => setSuccessMessage("")}
        message={successMessage}
      />
      {isLoading && <LoadingModal />}
      <ConfirmActionModal
        show={confirmDeleteGroup.activitygroup_id !== -1}
        onHide={() =>
          setConfirmDeleteGroup({ activitygroup_id: -1, order: -1 })
        }
        confirmAction={() => deleteActivityGroup(confirmDeleteGroup)}
        message={
          "Tem a certeza que pretende eliminar o grupo de atividades " +
          confirmDeleteGroup.order +
          "?"
        }
      />
    </>
  );
}
