import Head from "next/head";
import HomePage from "../components/homepage/homepage";

export default function Home() {
  return (
    <>
      <Head>
        <title>UNO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
    </>
  );
}
