import Head from "next/head";
import React from "react";

export default function Notes() {
  return (
    <>
      <Head>
        <title>UNO - Notas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container px-4">Em desenvolvimento...</div>
    </>
  );
}
