import Head from "next/head";

export default function Progress() {
  return (
    <>
      <Head>
        <title>UNO - Progresso</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container px-4">
        Em desenvolvimento...
      </div>
    </>
  );
}
