import Head from "next/head";

import { useEffect, useState } from "react";
import PageHeader from "../../../components/utils/page_header";
import { GetServerSideProps } from "next";
import SupportMaterialsService from "../../../services/supportmaterials.service";
import { useSelector } from "react-redux";
import { RootState } from "../../../redux/store";
import { ActiveClassState } from "../../../redux/features/active_class";
import Loading from "../../../components/utils/loading";
import Material from "../../../components/contents/supportmaterials/material";
import ErrorCard from "../../../components/utils/error_card";

interface SupportMaterialProps {
  supportmaterial_id: number;
}

export type SupportMaterialType = {
  id: number;
  order: number;
  title: string;
  description: string;
  media_type: string | null;
};

export default function SupportMaterial({
  supportmaterial_id,
}: SupportMaterialProps) {
  const [isPageLoading, setIsPageLoading] = useState(false);
  const [error, setError] = useState(false);

  const { id: class_id } = useSelector<RootState, ActiveClassState>(
    (state) => state.active_class
  );

  const [supportmaterial, setSupportMaterial] = useState<SupportMaterialType>();

  useEffect(() => {
    setIsPageLoading(true);
    SupportMaterialsService.getMaterial(class_id, supportmaterial_id)
      .then((data) => {
        setSupportMaterial(data);
      })
      .catch((err) => {
        setError(true);
      })
      .finally(() => {
        setIsPageLoading(false);
      });
  }, [class_id, supportmaterial_id]);

  if (isPageLoading) {
    return <Loading />;
  }

  return (
    <>
      <Head>
        <title>UNO - Materiais de apoio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container px-4">
        <div className="row g-3 mt-2 mb-4">
          <PageHeader header_text={supportmaterial?.order + ". " + supportmaterial?.title} />
        </div>

        { error &&
          <div className="row g-3 my-2">
            <ErrorCard message="Ocorreu um erro ao obter a informação do material de apoio. Por favor tente novamente." />
          </div>
        }

        {supportmaterial != undefined &&
          <Material
            supportmaterial_id={supportmaterial.id}
            title={supportmaterial.title}
            description={supportmaterial.description}
            media_type={supportmaterial.media_type}
          />
        }
        
      </div>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const supportmaterial_id = context.query.id;

  return {
    props: {
      supportmaterial_id: supportmaterial_id,
    },
  };
};
