import Head from "next/head";

import { useState } from "react";
import PageHeader from "../../../components/utils/page_header";
import ErrorModal from "../../../components/utils/error_modal";
import SuccessModal from "../../../components/utils/success_modal";
import LoadingModal from "../../../components/utils/loading_modal";
import MaterialForm from "../../../components/contents/supportmaterials/material_form";

export default function NewSupportMaterial() {
  const [errorMessage, setErrorMessage] = useState("");
  const [successMessage, setSuccessMessage] = useState("");
  const [isLoading, setIsLoading] = useState(false);

  return (
    <>
      <Head>
        <title>UNO - Materiais de apoio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container px-4">
        <div className="row g-3 mt-2 mb-4">
          <PageHeader
            header_text="Novo material de apoio"
          />
        </div>

        <MaterialForm
          setIsLoading={setIsLoading}
          setErrorMessage={setErrorMessage}
          setSuccessMessage={setSuccessMessage}
        />
        
      </div>

      <ErrorModal
        show={errorMessage !== ""}
        onHide={() => setErrorMessage("")}
        message={errorMessage}
      />
      <SuccessModal
        show={successMessage !== ""}
        onHide={() => {
          setSuccessMessage("");
        }}
        message={successMessage}
        button_link_path={`/contents/supportmaterials`}
      />
      {isLoading && <LoadingModal />}
    </>
  );
}
