import Head from "next/head";
import PageCard from "../../components/utils/page_card";

export default function Contents() {
  return (
    <>
      <Head>
        <title>UNO - Conteúdos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container px-4">
        <div className="row g-3 my-2">
          <div className="col-lg-6">
            <PageCard
              header="Grupos de atividades"
              text="Gerencie os conteúdos e exercícios das suas turmas."
              path="/contents/groups"
            />
          </div>
          <div className="col-lg-6">
            <PageCard
              header="Materiais de apoio"
              text="Gerencie o material de apoio das suas turmas."
              path="/contents/library"
            />
          </div>
        </div>
      </div>
    </>
  );
}
