name: Deploy

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image for API
        uses: docker/build-push-action@v2
        with:
          context: ./UNOServer
          dockerfile: ./UNOServer/Dockerfile
          push: true
          tags: rafaelbaptista13/uno_api:latest

      - name: Build and push Docker image for WebApp
        uses: docker/build-push-action@v2
        with:
          context: ./unoweb
          dockerfile: ./unoweb/Dockerfile
          push: true
          tags: rafaelbaptista13/uno_webapp:latest

      - name: Install Docker Compose
        uses: docker/compose-cli@v1.0.31

      - name: Deploy Docker Compose stack
        uses: docker/compose@v2.0.0
        with:
          compose-file: docker-compose.yml
          project-name: uno
          command: up -d
