name: Deploy

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: rafaelbaptista13/uno:latest

      - name: Deploy Docker Compose stack
        uses: docker/compose-action@v1
        with:
          compose-file: docker-compose.yml
          project-name: your-project-name
          command: up -d
